export const POST = {
  GET_ALL: "GET_ALL_POST",
  GET_BY_ID: "GET_POST_BY_ID",
  DELETE: "DELETE_POST",
  CREATE: "CREATE_POST",
  EDIT: "EDIT_POST"
}

export const USER = {
  GET_ALL: "GET_ALL_USER"
}

export const SIDE_BAR = {
  ACTIVE: "ATIVE_SIDE_BAR",
  HIDE: "HIDE_SIDE_BAR"
}

export const CONFIRM_DIALOG = {
  OPEN: "OPEN_CONFIRM_DIALOG",
  CLOSE: "CLOSE_CONFIRM_DIALOG"
}

export const FORM_DIALOG = {
  OPEN: "OPEN_FORM_DIALOG",
  CLOSE: "CLOSE_FORM_DIALOG"
}

export const MESSAGE = {
  OPEN: "OPEN_MESSAGE",
  CLOSE: "CLOSE_MESSAGE"
}

export const FORM_STATE = {
  IS_EDITING: "FORM_IS_EDITING",
  RESET: "RESET_FORM_STATE"
}
